In [70]:
import numpy as np
import pandas as pd

In [71]:
data = {
    'Name' : ['john' , 'Anna' , 'peter' , 'linda'],
    'Age' : [28 , 34 , 29 , 42],
    'city' : ['New York' , 'paris' , 'Berlin' , "London"],
    'Salary' : [65000 , 70000 , 62000 , 85000]
}

df = pd.DataFrame(data)

In [72]:
data_list = [
    ['John' , 28 , 'New York' , 65000],
    ['Anna' , 34 ,'Paris' , 70000],
    ['Peter', 29 , 'Berlin' , 62000],
    ['Linda' , 42 , 'London' , 85000]
]

df2 = pd.DataFrame(data_list , columns = ['Name', 'Age' , 'City' , 'Salary'])
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [73]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [74]:
df2[['Age' , 'Salary']]

   Age  Salary
0   28   65000
1   34   70000
2   29   62000
3   42   85000

In [75]:
df2["Designation"] = ["Doctor" , "Engineer" , "Doctor" , "Emgineer"]

In [76]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Emgineer

Remove a Column

In [77]:
df2.drop('Designation' , axis = 1 , inplace = True)

In [78]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [79]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [80]:
df2.loc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [81]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [82]:
df2.loc[[0,1]] [['City' , 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [83]:
df2.loc[[2,3]][['Name' , 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Statement

In [84]:
#I only want to see those people whose age is above 30
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [85]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [86]:
#I only want people whose age is above 30 and their city is paris

In [90]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000